name: Fetch Stock Daily

on:
  schedule:
    - cron: "0 8 * * *" # 收盘后16: 00运行，即UTC 时间 08:00
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-timeline:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      PGURL: ${{ secrets.PGURL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run script
        run: bun run scripts/daily.ts
